module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Users',
      [
        {
          login: 11065,
          password: 11065,
          surname: 'Гнутов',
          name: 'Федор',
          patronymic: 'Александрович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 223,
          password: 223,
          surname: 'Гордеев',
          name: 'Николай',
          patronymic: 'Леонидович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 9552,
          password: 9552,
          surname: 'Егорченкова',
          name: 'Елизавета',
          patronymic: 'Алексеевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 2122,
          password: 2122,
          surname: 'Кушпель',
          name: 'Надежда',
          patronymic: 'Николаевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 3629,
          password: 3629,
          surname: 'Певзнер',
          name: 'Игорь',
          patronymic: 'Михайлович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 1029,
          password: 1029,
          surname: 'Хамов',
          name: 'Геннадий',
          patronymic: 'Григорьевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 1127,
          password: 1127,
          surname: 'Яшина',
          name: 'Елена',
          patronymic: 'Юрьевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 5209,
          password: 5209,
          surname: 'Антипова',
          name: 'Любовь',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 159,
          password: 159,
          surname: 'Вернер',
          name: 'Алексей',
          patronymic: 'Леонидович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 7607,
          password: 7607,
          surname: 'Далевская',
          name: 'Ольга',
          patronymic: 'Петровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 4789,
          password: 4789,
          surname: 'Маслова',
          name: 'Юлия',
          patronymic: 'Валерьевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 1266,
          password: 1266,
          surname: 'Нежинский',
          name: 'Владимир',
          patronymic: 'Михайлович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 5205,
          password: 5205,
          surname: 'Нестеренок',
          name: 'Вадим',
          patronymic: 'Владимирович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 11067,
          password: 11067,
          surname: 'Петров',
          name: 'Максим',
          patronymic: 'Викторович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 1323,
          password: 1323,
          surname: 'Степанова',
          name: 'Марина',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 1033,
          password: 1033,
          surname: 'Ходот',
          name: 'Татьяна',
          patronymic: 'Георгиевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 2,
        },
        {
          login: 1273,
          password: 1273,
          surname: 'Аркина',
          name: 'Ксения',
          patronymic: 'Георгиевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 1405,
          password: 1405,
          surname: 'Будаев',
          name: 'Виктор',
          patronymic: 'Дмитриевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 11453,
          password: 11453,
          surname: 'Конькина',
          name: 'Вероника',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 1557,
          password: 1557,
          surname: 'Линчук',
          name: 'Лидия',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 9464,
          password: 9464,
          surname: 'Лиховодова',
          name: 'Татьяна',
          patronymic: 'Борисовна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 10362,
          password: 10362,
          surname: 'Павлов',
          name: 'Дмитрий',
          patronymic: 'Александрович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 822,
          password: 822,
          surname: 'Рисс',
          name: 'Елена',
          patronymic: 'Артуровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 841,
          password: 841,
          surname: 'Рукшин',
          name: 'Сергей',
          patronymic: 'Евгеньевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 4184,
          password: 4184,
          surname: 'Суслина',
          name: 'Мария',
          patronymic: 'Евгеньевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 11456,
          password: 11456,
          surname: 'Фофанов',
          name: 'Кирилл',
          patronymic: 'Алексеевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 10078,
          password: 10078,
          surname: 'Широков',
          name: 'Николай',
          patronymic: 'Алексеевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 2229,
          password: 2229,
          surname: 'Клещева',
          name: 'Ирина',
          patronymic: 'Валерьевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 11049,
          password: 11049,
          surname: 'Кожокарь',
          name: 'Ольга',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 499,
          password: 499,
          surname: 'Кочуренко',
          name: 'Надежда',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 511,
          password: 511,
          surname: 'Крылов',
          name: 'Валерий',
          patronymic: 'Валентинович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 571,
          password: 571,
          surname: 'Лисимова',
          name: 'Ольга',
          patronymic: 'Анатольевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 582,
          password: 582,
          surname: 'Лопачев',
          name: 'Владимир',
          patronymic: 'Александрович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 1244,
          password: 1244,
          surname: 'Орлов',
          name: 'Владимир',
          patronymic: 'Викторович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 727,
          password: 727,
          surname: 'Пиотровская',
          name: 'Ксения',
          patronymic: 'Раймондовна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 738,
          password: 738,
          surname: 'Подходова',
          name: 'Наталья',
          patronymic: 'Семеновна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 8873,
          password: 8873,
          surname: 'Пратусевич',
          name: 'Максим',
          patronymic: 'Яковлевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 858,
          password: 858,
          surname: 'Сазонова',
          name: 'Наталья',
          patronymic: 'Викторовна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 1345,
          password: 1345,
          surname: 'Снегурова',
          name: 'Виктория',
          patronymic: 'Игоревна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 10647,
          password: 10647,
          surname: 'Солдаева',
          name: 'Мария',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 945,
          password: 945,
          surname: 'Стефанова',
          name: 'Наталия',
          patronymic: 'Леонидовна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 8648,
          password: 8648,
          surname: 'Тербушева',
          name: 'Екатерина',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 2206,
          password: 2206,
          surname: 'Шумара',
          name: 'Елена',
          patronymic: 'Викторовна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 4,
        },
        {
          login: 7596,
          password: 7596,
          surname: 'Байгузева',
          name: 'Александра',
          patronymic: 'Петровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 5,
        },
        {
          login: 4116,
          password: 4116,
          surname: 'Пальтиель',
          name: 'Лев',
          patronymic: 'Романович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 6,
        },
        {
          login: 937,
          password: 937,
          surname: 'Спивак',
          name: 'Веда',
          patronymic: 'Игоревна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 7,
        },
        {
          login: 138,
          password: 138,
          surname: 'Васильев',
          name: 'Владимир',
          patronymic: 'Ефимович',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 8,
        },
        {
          login: 999999,
          password: 999999,
          surname: 'Ерошкина',
          name: 'Ольга',
          patronymic: 'Николаевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 9,
        },
        {
          login: 2795,
          password: 2795,
          surname: 'Лагутина',
          name: 'Анна',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 10,
        },
        {
          login: 313,
          password: 313,
          surname: 'Жаркой',
          name: 'Александр',
          patronymic: 'Борисович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 11,
        },
        {
          login: 1882,
          password: 1882,
          surname: 'Кудрявцева',
          name: 'Ирина',
          patronymic: 'Андреевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 12,
        },
        {
          login: 999998,
          password: 999998,
          surname: 'Михайлов',
          name: 'Александр',
          patronymic: 'Борисович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 1,
        },
        {
          login: 122978,
          password: 122978,
          surname: 'Ахмедова',
          name: 'Людмила',
          patronymic: 'Гаджимурадовна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122953,
          password: 122953,
          surname: 'Березина',
          name: 'Алина',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 113623,
          password: 113623,
          surname: 'Богачёв',
          name: 'Владимир',
          patronymic: 'Александрович',
          isMale: 1,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 125566,
          password: 125566,
          surname: 'Громова',
          name: 'Елизавета',
          patronymic: 'Андреевна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122941,
          password: 122941,
          surname: 'Карпушина',
          name: 'Марьяна',
          patronymic: 'Дмитриевна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122954,
          password: 122954,
          surname: 'Курочкина',
          name: 'Полина',
          patronymic: 'Евгеньевна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122927,
          password: 122927,
          surname: 'Малиновская',
          name: 'Алиса',
          patronymic: 'Витальевна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122972,
          password: 122972,
          surname: 'Николаева',
          name: 'Лилия',
          patronymic: 'Аркадьевна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122945,
          password: 122945,
          surname: 'Острийчук',
          name: 'Александр',
          patronymic: 'Александрович',
          isMale: 1,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122990,
          password: 122990,
          surname: 'Светляков',
          name: 'Юрий',
          patronymic: 'Иванович',
          isMale: 1,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122938,
          password: 122938,
          surname: 'Сергеева',
          name: 'Екатерина',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 127759,
          password: 127759,
          surname: 'Трескунова',
          name: 'Рахель',
          patronymic: 'Михайловна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122987,
          password: 122987,
          surname: 'Яковлева',
          name: 'Дарья',
          patronymic: 'Эдуардовна',
          isMale: 0,
          role: 'student',
          groupId: 1,
          departmentId: null,
        },
        {
          login: 122929,
          password: 122929,
          surname: 'Ануфриева',
          name: 'Оксана',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122947,
          password: 122947,
          surname: 'Боденчук',
          name: 'Екатерина',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122955,
          password: 122955,
          surname: 'Боровкова',
          name: 'Екатерина',
          patronymic: 'Юрьевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 125199,
          password: 125199,
          surname: 'Дмитриева',
          name: 'Кристина',
          patronymic: 'Валентиновна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122940,
          password: 122940,
          surname: 'Землякова',
          name: 'Александра',
          patronymic: 'Алексеевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 117795,
          password: 117795,
          surname: 'Зубиетян',
          name: 'Артем',
          patronymic: 'Каренович',
          isMale: 1,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122994,
          password: 122994,
          surname: 'Казымова',
          name: 'Лейла',
          patronymic: 'Натиговна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122966,
          password: 122966,
          surname: 'Копытова',
          name: 'Ирина',
          patronymic: 'Дмитриевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122952,
          password: 122952,
          surname: 'Лапалайнен',
          name: 'Маргарита',
          patronymic: 'Романовна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 126288,
          password: 126288,
          surname: 'Новицкая',
          name: 'Валерия',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122971,
          password: 122971,
          surname: 'Нужная',
          name: 'Дарья',
          patronymic: 'Дмитриевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122974,
          password: 122974,
          surname: 'Рудых',
          name: 'Анастасия',
          patronymic: 'Андреевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122983,
          password: 122983,
          surname: 'Смирнова',
          name: 'Дарья',
          patronymic: 'Романовна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122982,
          password: 122982,
          surname: 'Халапова',
          name: 'Сабина',
          patronymic: 'Эмильевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122946,
          password: 122946,
          surname: 'Ятченко',
          name: 'Анна',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 2,
          departmentId: null,
        },
        {
          login: 122948,
          password: 122948,
          surname: 'Амосёнок',
          name: 'Анастасия',
          patronymic: 'Дмитриевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122958,
          password: 122958,
          surname: 'Андреева',
          name: 'Мария',
          patronymic: 'Андреевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122993,
          password: 122993,
          surname: 'Воронина',
          name: 'Полина',
          patronymic: 'Олеговна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122936,
          password: 122936,
          surname: 'Евграфова',
          name: 'Анастасия',
          patronymic: 'Андреевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122968,
          password: 122968,
          surname: 'Зайцева',
          name: 'Елизавета',
          patronymic: 'Алексеевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122984,
          password: 122984,
          surname: 'Захарова',
          name: 'Ангелина',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122957,
          password: 122957,
          surname: 'Йазыджы',
          name: 'София',
          patronymic: 'Алиевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 123730,
          password: 123730,
          surname: 'Калугина',
          name: 'Ольга',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122944,
          password: 122944,
          surname: 'Карсакова',
          name: 'Дарья',
          patronymic: 'Олеговна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122988,
          password: 122988,
          surname: 'Конарева',
          name: 'Наталья',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122939,
          password: 122939,
          surname: 'Корехова',
          name: 'Дина',
          patronymic: 'Алексеевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122934,
          password: 122934,
          surname: 'Кузьменкова',
          name: 'Елизавета',
          patronymic: 'Игоревна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 126388,
          password: 126388,
          surname: 'Оразова',
          name: 'Мяхриджемал',
          patronymic: '',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122979,
          password: 122979,
          surname: 'Саламатина',
          name: 'Юлия',
          patronymic: 'Алексеевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 132867,
          password: 132867,
          surname: 'Самойлова',
          name: 'Людмила',
          patronymic: 'Дмитриевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122960,
          password: 122960,
          surname: 'Сердюк',
          name: 'Олеся',
          patronymic: 'Эльнуровна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122951,
          password: 122951,
          surname: 'Соколова',
          name: 'Анастасия',
          patronymic: 'Денисовна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 125269,
          password: 125269,
          surname: 'Тулумбасова',
          name: 'Маргарита',
          patronymic: 'Михайловна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122963,
          password: 122963,
          surname: 'Чуксина',
          name: 'Дарья',
          patronymic: 'Андреевна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 122980,
          password: 122980,
          surname: 'Шкляева',
          name: 'Мария',
          patronymic: 'Викторовна',
          isMale: 0,
          role: 'student',
          groupId: 3,
          departmentId: null,
        },
        {
          login: 118299,
          password: 118299,
          surname: 'Баринова',
          name: 'Анастасия',
          patronymic: 'Андреевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118284,
          password: 118284,
          surname: 'Берко',
          name: 'Екатерина',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 120773,
          password: 120773,
          surname: 'Бизякина',
          name: 'Дарья',
          patronymic: 'Витальевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 120774,
          password: 120774,
          surname: 'Воробьев',
          name: 'Никита',
          patronymic: ' Александрович',
          isMale: 1,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 117811,
          password: 117811,
          surname: 'Воробьева',
          name: 'Олеся',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118278,
          password: 118278,
          surname: 'Жукова',
          name: 'Алина',
          patronymic: 'Ивановна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118257,
          password: 118257,
          surname: 'Зозуля',
          name: 'Анастасия',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118289,
          password: 118289,
          surname: 'Капалбаева',
          name: 'Эльвира',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118282,
          password: 118282,
          surname: 'Кудрявцева',
          name: 'Маргарита',
          patronymic: 'Викторовна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118309,
          password: 118309,
          surname: 'Кулагина',
          name: 'Марианна',
          patronymic: 'Олеговна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 120766,
          password: 120766,
          surname: 'Лукша',
          name: 'Екатерина',
          patronymic: 'Борисовна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118287,
          password: 118287,
          surname: 'Наумова',
          name: 'Любовь',
          patronymic: 'Борисовна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118268,
          password: 118268,
          surname: 'Семенова',
          name: 'Элина',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118280,
          password: 118280,
          surname: 'Сергеева',
          name: 'Лидия',
          patronymic: 'Евгеньевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118078,
          password: 118078,
          surname: 'Сорокина',
          name: 'Елизавета',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118274,
          password: 118274,
          surname: 'Столетова',
          name: 'Марина',
          patronymic: 'Вячеславовна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118308,
          password: 118308,
          surname: 'Ступникова',
          name: 'Людмила',
          patronymic: 'Юрьевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118286,
          password: 118286,
          surname: 'Суворова',
          name: 'Анастасия',
          patronymic: 'Олеговна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 118276,
          password: 118276,
          surname: 'Трифонова',
          name: 'Александра',
          patronymic: 'Дмитриевна',
          isMale: 0,
          role: 'student',
          groupId: 5,
          departmentId: null,
        },
        {
          login: 120787,
          password: 120787,
          surname: 'Блохин',
          name: 'Иван',
          patronymic: 'Сергеевич',
          isMale: 1,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 118267,
          password: 118267,
          surname: 'Быкова',
          name: 'Александрина',
          patronymic: 'Александровна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 118295,
          password: 118295,
          surname: 'Голоулина',
          name: 'Елена',
          patronymic: 'Михайловна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 118292,
          password: 118292,
          surname: 'Денисенко',
          name: 'Анастасия',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 110782,
          password: 110782,
          surname: 'Дырина',
          name: 'Ольга',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 113640,
          password: 113640,
          surname: 'Елизарова',
          name: 'Дарья',
          patronymic: 'Витальевна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 118279,
          password: 118279,
          surname: 'Леонова',
          name: 'София',
          patronymic: 'Викторовна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 110680,
          password: 110680,
          surname: 'Романькина',
          name: 'Мария',
          patronymic: 'Генадиевна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 118310,
          password: 118310,
          surname: 'Соколов',
          name: 'Илья',
          patronymic: 'Антонович',
          isMale: 1,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 115758,
          password: 115758,
          surname: 'Цатурян',
          name: 'Рузанна',
          patronymic: 'Григорьевна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 120767,
          password: 120767,
          surname: 'Черенович',
          name: 'Виктория',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 118285,
          password: 118285,
          surname: 'Шаваринская',
          name: 'Елизавета',
          patronymic: 'Богдановна',
          isMale: 0,
          role: 'student',
          groupId: 6,
          departmentId: null,
        },
        {
          login: 118298,
          password: 118298,
          surname: 'Стефанов',
          name: 'Василий',
          patronymic: 'Владимирович',
          isMale: 1,
          role: 'student',
          groupId: 4,
          departmentId: null,
        },
        {
          login: 118312,
          password: 118312,
          surname: 'Сухорукова',
          name: 'Людмила',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 4,
          departmentId: null,
        },
        {
          login: 118271,
          password: 118271,
          surname: 'Томша',
          name: 'Анастасия',
          patronymic: 'Федоровна',
          isMale: 0,
          role: 'student',
          groupId: 4,
          departmentId: null,
        },
        {
          login: 118291,
          password: 118291,
          surname: 'Щербинина',
          name: 'Анастасия',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'student',
          groupId: 4,
          departmentId: null,
        },
        {
          login: 7558,
          password: 7558,
          surname: 'Краснов',
          name: 'Алексей',
          patronymic: 'Александрович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 13,
        },
        {
          login: 1122,
          password: 1122,
          surname: 'Якубсон',
          name: 'Михаил',
          patronymic: 'Яковлевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 3,
        },
        {
          login: 1280,
          password: 1280,
          surname: 'Ильина',
          name: 'Татьяна',
          patronymic: 'Сергеевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 14,
        },
        {
          login: 999997,
          password: 999997,
          surname: 'Жуковская',
          name: 'Галина',
          patronymic: 'Анатольевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 8,
        },
        {
          login: 999996,
          password: 999996,
          surname: 'Кудрявцева',
          name: 'Камила',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 15,
        },
        {
          login: 999995,
          password: 999995,
          surname: 'Свиридов',
          name: 'Сергей',
          patronymic: 'Александрович',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 16,
        },
        {
          login: 873,
          password: 873,
          surname: 'Седова',
          name: 'Нелля',
          patronymic: 'Владимировна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 17,
        },
        {
          login: 781,
          password: 781,
          surname: 'Поссель',
          name: 'Юлия',
          patronymic: 'Альфредовна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 18,
        },
        {
          login: 1622,
          password: 1622,
          surname: 'Яркин',
          name: 'Петр',
          patronymic: 'Алексеевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 19,
        },
        {
          login: 1402,
          password: 1402,
          surname: 'Спицына',
          name: 'Татьяна',
          patronymic: 'Анатольевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 20,
        },
        {
          login: 4132,
          password: 4132,
          surname: 'Ривкина',
          name: 'Светлана',
          patronymic: 'Викторовна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 21,
        },
        {
          login: 806,
          password: 806,
          surname: 'Разумова',
          name: 'Ольга',
          patronymic: 'Юрьевна',
          isMale: 0,
          role: 'professor',
          groupId: null,
          departmentId: 22,
        },
        {
          login: 999994,
          password: 999994,
          surname: 'Гончарко',
          name: 'Дмитрий',
          patronymic: 'Николаевич',
          isMale: 1,
          role: 'professor',
          groupId: null,
          departmentId: 7,
        },
        {
          login: 10000,
          password: 10000,
          surname: 'Котова',
          name: 'Анастасия',
          patronymic: 'Владиславовна',
          isMale: 0,
          role: 'admin',
          groupId: null,
          departmentId: null,
        },
        {
          surname: 'Шкляева',
          name: 'Марина',
          patronymic: 'Викторовна',
          formOfEducation: 'Бюджет',
          login: 150000,
          password: 150000,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Дорошенко',
          name: 'Ульяна',
          patronymic: 'Максимовна',
          formOfEducation: 'Бюджет',
          login: 150001,
          password: 150001,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Москва',
        },
        {
          surname: 'Степанова',
          name: 'Елизавета',
          patronymic: 'Павловна',
          formOfEducation: 'Бюджет',
          login: 150002,
          password: 150002,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Коммисаров',
          name: 'Роман',
          patronymic: 'Анатольевич',
          formOfEducation: 'Бюджет',
          login: 150003,
          password: 150003,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Северодвинск',
        },
        {
          surname: 'Зайцева',
          name: 'Елизавета',
          patronymic: 'Алексеевна',
          formOfEducation: 'Бюджет',
          login: 150004,
          password: 150004,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Москва',
        },
        {
          surname: 'Боденчук',
          name: 'Екатерина',
          patronymic: 'Владимировна',
          formOfEducation: 'Бюджет',
          login: 150005,
          password: 150005,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Архангельск',
        },
        {
          surname: 'Саламатина',
          name: 'Юлия',
          patronymic: 'Алексеевна',
          formOfEducation: 'Бюджет',
          login: 150006,
          password: 150006,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Васина',
          name: 'Мария',
          patronymic: 'Витальевна',
          formOfEducation: 'Бюджет',
          login: 150007,
          password: 150007,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Липецк',
        },
        {
          surname: 'Землякова',
          name: 'Александра',
          patronymic: 'Алексеевна',
          formOfEducation: 'Бюджет',
          login: 150008,
          password: 150008,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Сердюк',
          name: 'Олеся',
          patronymic: 'Эльнуровна',
          formOfEducation: 'Бюджет',
          login: 150009,
          password: 150009,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Екатеринбург',
        },
        {
          surname: 'Чуксина',
          name: 'Дарья',
          patronymic: 'Андреевна',
          formOfEducation: 'Бюджет',
          login: 150010,
          password: 150010,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Уфа',
        },
        {
          surname: 'Йазыджы',
          name: 'София',
          patronymic: 'Алиевна',
          formOfEducation: 'Бюджет',
          login: 150011,
          password: 150011,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Андреева',
          name: 'Мария',
          patronymic: 'Андреевна',
          formOfEducation: 'Бюджет',
          login: 150012,
          password: 150012,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Краснодар',
        },
        {
          surname: 'Рудых',
          name: 'Анастасия',
          patronymic: 'Андреевна',
          formOfEducation: 'Бюджет',
          login: 150013,
          password: 150013,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Екатеринбург',
        },
        {
          surname: 'Евграфова',
          name: 'Анастасия',
          patronymic: 'Андреевна',
          formOfEducation: 'Бюджет',
          login: 150014,
          password: 150014,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Николаев',
          name: 'Даниил',
          patronymic: 'Игоревич',
          formOfEducation: 'Бюджет',
          login: 150015,
          password: 150015,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Нижний Новгород',
        },
        {
          surname: 'Нужная',
          name: 'Дарья',
          patronymic: 'Дмитриевна',
          formOfEducation: 'Бюджет',
          login: 150016,
          password: 150016,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Красноярск',
        },
        {
          surname: 'Карсакова',
          name: 'Дарья',
          patronymic: 'Олеговна',
          formOfEducation: 'Бюджет',
          login: 150017,
          password: 150017,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Боровкова',
          name: 'Екатерина',
          patronymic: 'Юрьевна',
          formOfEducation: 'Бюджет',
          login: 150018,
          password: 150018,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Кузьменкова',
          name: 'Елизавета',
          patronymic: 'Игоревна',
          formOfEducation: 'Бюджет',
          login: 150019,
          password: 150019,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Севастополь',
        },
        {
          surname: 'Ятченко',
          name: 'Анна',
          patronymic: 'Сергеевна',
          formOfEducation: 'Бюджет',
          login: 150020,
          password: 150020,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Сочи',
        },
        {
          surname: 'Гришина',
          name: 'Виктория',
          patronymic: 'Романовна',
          formOfEducation: 'Бюджет',
          login: 150021,
          password: 150021,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Гаврис',
          name: 'Полина',
          patronymic: 'Владимировна',
          formOfEducation: 'Бюджет',
          login: 150022,
          password: 150022,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Северодвинск',
        },
        {
          surname: 'Марченко',
          name: 'Маргарита',
          patronymic: 'Романовна',
          formOfEducation: 'Бюджет',
          login: 150023,
          password: 150023,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Амосёнок',
          name: 'Анастасия',
          patronymic: 'Дмитриевна',
          formOfEducation: 'Бюджет',
          login: 150024,
          password: 150024,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Копытова',
          name: 'Ирина',
          patronymic: 'Дмитриевна',
          formOfEducation: 'Бюджет',
          login: 150025,
          password: 150025,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Москва',
        },
        {
          surname: 'Воронина',
          name: 'Полина',
          patronymic: 'Олеговна',
          formOfEducation: 'Платное',
          login: 150026,
          password: 150026,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Москва',
        },
        {
          surname: 'Гольтяева',
          name: 'Софья',
          patronymic: 'Николаевна',
          formOfEducation: 'Бюджет',
          login: 150027,
          password: 150027,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Дакирова',
          name: 'Агниет',
          patronymic: 'Абылайхановна',
          formOfEducation: 'Бюджет',
          login: 150028,
          password: 150028,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Симферополь',
        },
        {
          surname: 'Квашнина',
          name: 'Юлия',
          patronymic: 'Сергеевна',
          formOfEducation: 'Бюджет',
          login: 150029,
          password: 150029,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Ануфриева',
          name: 'Оксана',
          patronymic: 'Сергеевна',
          formOfEducation: 'Целевое',
          login: 150030,
          password: 150030,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Соколова',
          name: 'Анастасия',
          patronymic: 'Денисовна',
          formOfEducation: 'Бюджет',
          login: 150031,
          password: 150031,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Екатеринбург',
        },
        {
          surname: 'Смирнова',
          name: 'Дарья',
          patronymic: 'Романовна',
          formOfEducation: 'Бюджет',
          login: 150032,
          password: 150032,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Девришева',
          name: 'Альбина',
          patronymic: 'Эльшадовна',
          formOfEducation: 'Бюджет',
          login: 150033,
          password: 150033,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Корехова',
          name: 'Дина',
          patronymic: 'Алексеевна',
          formOfEducation: 'Бюджет',
          login: 150034,
          password: 150034,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Москва',
        },
        {
          surname: 'Новицкая',
          name: 'Валерия',
          patronymic: 'Александровна',
          formOfEducation: 'Платное',
          login: 150035,
          password: 150035,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Швечихина',
          name: 'Анастасия',
          patronymic: 'Александровна',
          formOfEducation: 'Платное',
          login: 150036,
          password: 150036,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Захарова',
          name: 'Ангелина',
          patronymic: 'Александровна',
          formOfEducation: 'Бюджет',
          login: 150037,
          password: 150037,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Юхненко',
          name: 'Кристина',
          patronymic: 'Валентиновна',
          formOfEducation: 'Платное',
          login: 150038,
          password: 150038,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Екатеринбург',
        },
        {
          surname: 'Конарева',
          name: 'Наталья',
          patronymic: 'Владимировна',
          formOfEducation: 'Бюджет',
          login: 150039,
          password: 150039,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Абдуселимова',
          name: 'Оксана',
          patronymic: 'Аликеримовна',
          formOfEducation: 'Целевое',
          login: 150040,
          password: 150040,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Стативка',
          name: 'Ирина',
          patronymic: 'Сергеевна',
          formOfEducation: 'Платное',
          login: 150041,
          password: 150041,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Норильск',
        },
        {
          surname: 'Джашеева',
          name: 'Танзиля',
          patronymic: 'Кямаловна',
          formOfEducation: 'Бюджет',
          login: 150042,
          password: 150042,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Потапенко',
          name: 'Максим',
          patronymic: 'Алексеевич',
          formOfEducation: 'Бюджет',
          login: 150043,
          password: 150043,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Тулумбасова',
          name: 'Маргарита',
          patronymic: 'Михайловна',
          formOfEducation: 'Платное',
          login: 150044,
          password: 150044,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Архангельск',
        },
        {
          surname: 'Мартынович',
          name: 'Екатерина',
          patronymic: 'Артуровна',
          formOfEducation: 'Платное',
          login: 150045,
          password: 150045,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Екатеринбург',
        },
        {
          surname: 'Грушина',
          name: 'Анна',
          patronymic: 'Юрьевна',
          formOfEducation: 'Целевое',
          login: 150046,
          password: 150046,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Нижневартовск',
        },
        {
          surname: 'Халапова',
          name: 'Сабина',
          patronymic: 'Эмильевна',
          formOfEducation: 'Бюджет',
          login: 150047,
          password: 150047,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Владикавказ',
        },
        {
          surname: 'Синельникова',
          name: 'Евгения',
          patronymic: 'Константиновна',
          formOfEducation: 'Целевое',
          login: 150048,
          password: 150048,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Лебедева',
          name: 'Полина',
          patronymic: 'Александровна',
          formOfEducation: 'Целевое',
          login: 150049,
          password: 150049,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Екатеринбург',
        },
        {
          surname: 'Казымова',
          name: 'Лейла',
          patronymic: 'Натиговна',
          formOfEducation: 'Платное',
          login: 150050,
          password: 150050,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Москва',
        },
        {
          surname: 'Заболотная',
          name: 'Екатерина',
          patronymic: 'Андреена',
          formOfEducation: 'Платное',
          login: 150051,
          password: 150051,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Волкова',
          name: 'ОЛьга',
          patronymic: 'Андреевна',
          formOfEducation: 'Платное',
          login: 150052,
          password: 150052,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Екатеринбург',
        },
        {
          surname: 'Исмоилов',
          name: 'Амиржон',
          patronymic: 'Умеджонович',
          formOfEducation: 'Платное',
          login: 150053,
          password: 150053,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Ерина',
          name: 'Алёна',
          patronymic: 'Геннадьевна',
          formOfEducation: 'Бюджет',
          login: 150054,
          password: 150054,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Прокофьев',
          name: 'Даниил',
          patronymic: 'Дмитриевич',
          formOfEducation: 'Платное',
          login: 150055,
          password: 150055,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Самойлова',
          name: 'Софья',
          patronymic: 'Павловна',
          formOfEducation: 'Бюджет',
          login: 150056,
          password: 150056,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Яковлева',
          name: 'Елизавета',
          patronymic: 'Александровна',
          formOfEducation: 'Платное',
          login: 150057,
          password: 150057,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Архангельск',
        },
        {
          surname: 'Божеловская',
          name: 'Алина',
          patronymic: 'Николаевна',
          formOfEducation: 'Платное',
          login: 150058,
          password: 150058,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Смирнова',
          name: 'Аксинья',
          patronymic: 'Васильевна',
          formOfEducation: 'Платное',
          login: 150059,
          password: 150059,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Яголковский',
          name: 'Алексей',
          patronymic: 'Вадимович',
          formOfEducation: 'Платное',
          login: 150060,
          password: 150060,
          role: 'abiturient',
          directing: '44.03.01',
          age: 18,
          city: 'Екатеринбург',
        },
        {
          surname: 'Корепанова',
          name: 'Алёна',
          patronymic: 'Николаевна',
          formOfEducation: 'Платное',
          login: 150061,
          password: 150061,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Москва',
        },
        {
          surname: 'Левченко',
          name: 'Захар',
          patronymic: 'Андреевич',
          formOfEducation: 'Платное',
          login: 150062,
          password: 150062,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Санкт-Петербург',
        },
        {
          surname: 'Лубрикова',
          name: 'Елизавета',
          patronymic: 'Сергеевна',
          formOfEducation: 'Платное',
          login: 150063,
          password: 150063,
          role: 'abiturient',
          directing: '44.03.01',
          age: 19,
          city: 'Екатеринбург',
        },
        {
          surname: 'Зиябеков',
          name: 'Сухроб',
          patronymic: 'Олимджонович',
          formOfEducation: 'Платное',
          login: 150064,
          password: 150064,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Северодвинск',
        },
        {
          surname: 'Азадов',
          name: 'Джахонгир',
          patronymic: 'Алишер угли',
          formOfEducation: 'Платное',
          login: 150065,
          password: 150065,
          role: 'abiturient',
          directing: '44.03.01',
          age: 17,
          city: 'Санкт-Петербург',
        },
      ].map((item) => ({
        ...item,
        createdAt: new Date(),
        updatedAt: new Date(),
        isMale: Boolean(item.isMale),
      })),
      {},
    );
  },
};
